import React, { useState } from "react";
import dark from "../styles/themes/dark";
import light from "../styles/themes/light";
import { ThemeProvider } from "styled-components";
import GlobalStyle from "../styles/GlobalStyles";

import Head from "next/head";
function MyApp({ Component, pageProps }) {
  const [theme, setTheme] = useState(dark);

  const toggleTheme = () => {
    setTheme(theme.title === "light" ? dark : light);
  };
  return (
    <React.Fragment>
      <Head>
        <title>Portfólio | Matheus Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Component
          {...pageProps}
          togleTheme={toggleTheme}
          theme={theme.title}
        />
        <GlobalStyle />
      </ThemeProvider>
    </React.Fragment>
  );
}

export default MyApp;
